### ISSUE TITLE
The main.py is not running

### ISSUE THREAD

**Issue by ayan-biswas0412** [dibschat/activity-recognition-KTH#1]
![Screenshot from 2020-04-09 14-08-06](https://user-images.githubusercontent.com/52851184/78875562-b54c7e80-7a6b-11ea-908b-0b6e3f35df3c.png)
it says list index out of range what to do with that .
the all required python modules are installed in my computer already as mentioned in your readme.please help

**Comment by dibschat** [comment]
The terminal should contain an argument with main.py
e.g. "python main.py process" / "python main.py train"
When you write only "python main.py", process = sys.argv[1] is getting out of range.
